### ISSUE TITLE
Non Compatibility with Dolphin, GOG and GCM

### ISSUE THREAD

**Issue by fouSieVa** [jacobgb24/gog-galaxy-dolphin#1]
Dear Jacob,
highly motivated I added your plugin into Gog. But GoG just find 1 Wii Game, out of my Collection. The Games aremostly GCM Data. Any Ideas to solve the Problem?

Greetings
Sieva!

**Comment by jacobgb24** [comment]
Hi, thanks for the feedback. I'll try to take a look at this soon. I only have `.iso` files to test with so it's likely the file format causing the issue.

**Comment by jacobgb24** [comment]
@fouSieVa I just made a small update to version `0.5`. Let me know if that fixes the issue for you.

**Comment by jacobgb24** [comment]
Closing for now. If the issue still exists, please reopen
