### ISSUE TITLE
Plugin crashing after ~10 seconds of connecting.

### ISSUE THREAD

**Issue by OsoaGitHub** [jacobgb24/gog-galaxy-dolphin#3]
The plugin crashes quickly after connecting and setting up, no games are added.

**Comment by jacobgb24** [comment]
Hi, can you provide some more details such as:

* Your operating system
* Version of GoG Galaxy
* What path you entered for Dolphin/games directory when setting up the plugin
* What games you are trying to add

**Comment by OsoaGitHub** [comment]
- Windows 10, latest version
- 2.0.37 Beta
- Dolphin path: `C:\Program Files\Dolphin`, Games path: `D:\Games\Dolphin`
- I'm just trying to add Ocarina of Time & Master Quest

**Comment by jacobgb24** [comment]
Hmm ok. I'm also on Windows and the same Galaxy version. 

Is the game you're trying to add an iso? I haven't tested other files formats.

It could also help if you uploaded the log files.
* Disconnect plugin (if it shows it's connected)
* Exit out of Galaxy
* Restart Galaxy
* Upload `C:\ProgramData\GOG.com\Galaxy\logs/ClientHelper.log` and `"C:\ProgramData\GOG.com\Galaxy\logs\plugin-ncube-c732be30-0407-463f-bc30-6d8b3809fef4.log"`

**Comment by t0mtee** [comment]
Sorry for late response, since this issue I have moved to Playnite instead of GOG Galaxy.
